### ISSUE TITLE
nice code

### ISSUE THREAD

**Issue by GrowlyX** [DecryptedHash/karma#1]
So since when did you own SolexGames?

**Comment by ItzBunniYT** [comment]
lmao?

**Comment by DecryptedHash** [comment]
mad ngl bunni sue me you stinky tranny and ill sue you for changing your gender pipe down you have no rights

**Comment by GrowlyX** [comment]
![image](https://user-images.githubusercontent.com/62861393/133912157-29e8ef7e-8ca4-471c-88e1-a4656d23d8b0.png)

**Comment by GrowlyX** [comment]
> mad ngl bunni sue me you stinky tranny and ill sue you for changing your gender pipe down you have no rights

Wait until you get sued :)
